set(WEBRTC_VERSION "4664")

import_remote(
	"https://webrtc.googlesource.com/src"
	TAG "branch-heads/${WEBRTC_VERSION}"
	GIT_CONFIG "add remote.origin.fetch +refs/branch-heads/*:refs/remotes/branch-heads/*"
	NO_CMAKE
	ALIAS webrtc_source
)
import_remote("https://github.com/abseil/abseil-cpp.git" TAG "lts_2022_06_23" NO_CMAKE ALIAS abseil_source)
import_remote("https://chromium.googlesource.com/libyuv/libyuv" TAG "master" NO_CMAKE ALIAS libyuv_source)

file(GLOB_RECURSE WEBRTC_LOCAL_SOURCES CONFIGURE_DEPENDS "${webrtc_source_path}/*/*.cc")
file(GLOB_RECURSE ABSEIL_LOCAL_SOURCES CONFIGURE_DEPENDS "${abseil_source_path}/*/*.cc")
list(FILTER WEBRTC_LOCAL_SOURCES EXCLUDE REGEX ".*/test")

set(webrtc_SOURCES
	${ABSEIL_LOCAL_SOURCES}
	${boringssl_source_path}/err_data.c
	${boringssl_source_path}/src/crypto/asn1/a_bitstr.c
	${boringssl_source_path}/src/crypto/asn1/a_bool.c
	${boringssl_source_path}/src/crypto/asn1/a_d2i_fp.c
	${boringssl_source_path}/src/crypto/asn1/a_dup.c
	${boringssl_source_path}/src/crypto/asn1/a_enum.c
	${boringssl_source_path}/src/crypto/asn1/a_gentm.c
	${boringssl_source_path}/src/crypto/asn1/a_i2d_fp.c
	${boringssl_source_path}/src/crypto/asn1/a_int.c
	${boringssl_source_path}/src/crypto/asn1/a_mbstr.c
	${boringssl_source_path}/src/crypto/asn1/a_object.c
	${boringssl_source_path}/src/crypto/asn1/a_octet.c
	${boringssl_source_path}/src/crypto/asn1/a_print.c
	${boringssl_source_path}/src/crypto/asn1/a_strnid.c
	${boringssl_source_path}/src/crypto/asn1/a_time.c
	${boringssl_source_path}/src/crypto/asn1/a_type.c
	${boringssl_source_path}/src/crypto/asn1/a_utctm.c
	${boringssl_source_path}/src/crypto/asn1/a_utf8.c
	${boringssl_source_path}/src/crypto/asn1/asn1_lib.c
	${boringssl_source_path}/src/crypto/asn1/asn1_par.c
	${boringssl_source_path}/src/crypto/asn1/asn_pack.c
	${boringssl_source_path}/src/crypto/asn1/f_enum.c
	${boringssl_source_path}/src/crypto/asn1/f_int.c
	${boringssl_source_path}/src/crypto/asn1/f_string.c
	${boringssl_source_path}/src/crypto/asn1/tasn_dec.c
	${boringssl_source_path}/src/crypto/asn1/tasn_enc.c
	${boringssl_source_path}/src/crypto/asn1/tasn_fre.c
	${boringssl_source_path}/src/crypto/asn1/tasn_new.c
	${boringssl_source_path}/src/crypto/asn1/tasn_typ.c
	${boringssl_source_path}/src/crypto/asn1/tasn_utl.c
	${boringssl_source_path}/src/crypto/asn1/time_support.c
	${boringssl_source_path}/src/crypto/base64/base64.c
	${boringssl_source_path}/src/crypto/bio/bio.c
	${boringssl_source_path}/src/crypto/bio/bio_mem.c
	${boringssl_source_path}/src/crypto/bio/connect.c
	${boringssl_source_path}/src/crypto/bio/fd.c
	${boringssl_source_path}/src/crypto/bio/file.c
	${boringssl_source_path}/src/crypto/bio/hexdump.c
	${boringssl_source_path}/src/crypto/bio/pair.c
	${boringssl_source_path}/src/crypto/bio/printf.c
	${boringssl_source_path}/src/crypto/bio/socket.c
	${boringssl_source_path}/src/crypto/bio/socket_helper.c
	${boringssl_source_path}/src/crypto/bn_extra/bn_asn1.c
	${boringssl_source_path}/src/crypto/bn_extra/convert.c
	${boringssl_source_path}/src/crypto/buf/buf.c
	${boringssl_source_path}/src/crypto/bytestring/asn1_compat.c
	${boringssl_source_path}/src/crypto/bytestring/ber.c
	${boringssl_source_path}/src/crypto/bytestring/cbb.c
	${boringssl_source_path}/src/crypto/bytestring/cbs.c
	${boringssl_source_path}/src/crypto/bytestring/unicode.c
	${boringssl_source_path}/src/crypto/chacha/chacha.c
	${boringssl_source_path}/src/crypto/cipher_extra/cipher_extra.c
	${boringssl_source_path}/src/crypto/cipher_extra/derive_key.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_aesctrhmac.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_aesgcmsiv.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_chacha20poly1305.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_null.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_rc2.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_rc4.c
	${boringssl_source_path}/src/crypto/cipher_extra/e_tls.c
	${boringssl_source_path}/src/crypto/cipher_extra/tls_cbc.c
	${boringssl_source_path}/src/crypto/cmac/cmac.c
	${boringssl_source_path}/src/crypto/conf/conf.c
	${boringssl_source_path}/src/crypto/cpu-aarch64-linux.c
	${boringssl_source_path}/src/crypto/cpu-arm-linux.c
	${boringssl_source_path}/src/crypto/cpu-arm.c
	${boringssl_source_path}/src/crypto/cpu-intel.c
	${boringssl_source_path}/src/crypto/cpu-ppc64le.c
	${boringssl_source_path}/src/crypto/crypto.c
	${boringssl_source_path}/src/crypto/curve25519/spake25519.c
	${boringssl_source_path}/src/crypto/dh/check.c
	${boringssl_source_path}/src/crypto/dh/dh.c
	${boringssl_source_path}/src/crypto/dh/dh_asn1.c
	${boringssl_source_path}/src/crypto/dh/params.c
	${boringssl_source_path}/src/crypto/digest_extra/digest_extra.c
	${boringssl_source_path}/src/crypto/dsa/dsa.c
	${boringssl_source_path}/src/crypto/dsa/dsa_asn1.c
	${boringssl_source_path}/src/crypto/ec_extra/ec_asn1.c
	${boringssl_source_path}/src/crypto/ecdh_extra/ecdh_extra.c
	${boringssl_source_path}/src/crypto/ecdsa_extra/ecdsa_asn1.c
	${boringssl_source_path}/src/crypto/engine/engine.c
	${boringssl_source_path}/src/crypto/err/err.c
	${boringssl_source_path}/src/crypto/evp/digestsign.c
	${boringssl_source_path}/src/crypto/evp/evp.c
	${boringssl_source_path}/src/crypto/evp/evp_asn1.c
	${boringssl_source_path}/src/crypto/evp/evp_ctx.c
	${boringssl_source_path}/src/crypto/evp/p_dsa_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_ec.c
	${boringssl_source_path}/src/crypto/evp/p_ec_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_ed25519.c
	${boringssl_source_path}/src/crypto/evp/p_ed25519_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_rsa.c
	${boringssl_source_path}/src/crypto/evp/p_rsa_asn1.c
	${boringssl_source_path}/src/crypto/evp/p_x25519.c
	${boringssl_source_path}/src/crypto/evp/p_x25519_asn1.c
	${boringssl_source_path}/src/crypto/evp/pbkdf.c
	${boringssl_source_path}/src/crypto/evp/print.c
	${boringssl_source_path}/src/crypto/evp/scrypt.c
	${boringssl_source_path}/src/crypto/evp/sign.c
	${boringssl_source_path}/src/crypto/ex_data.c
	${boringssl_source_path}/src/crypto/fipsmodule/bcm.c
	${boringssl_source_path}/src/crypto/fipsmodule/is_fips.c
	${boringssl_source_path}/src/crypto/fipsmodule/ecdh/ecdh.c
	${boringssl_source_path}/src/crypto/hkdf/hkdf.c
	${boringssl_source_path}/src/crypto/hrss/hrss.c
	${boringssl_source_path}/src/crypto/lhash/lhash.c
	${boringssl_source_path}/src/crypto/mem.c
	${boringssl_source_path}/src/crypto/obj/obj.c
	${boringssl_source_path}/src/crypto/obj/obj_xref.c
	${boringssl_source_path}/src/crypto/pem/pem_all.c
	${boringssl_source_path}/src/crypto/pem/pem_info.c
	${boringssl_source_path}/src/crypto/pem/pem_lib.c
	${boringssl_source_path}/src/crypto/pem/pem_oth.c
	${boringssl_source_path}/src/crypto/pem/pem_pk8.c
	${boringssl_source_path}/src/crypto/pem/pem_pkey.c
	${boringssl_source_path}/src/crypto/pem/pem_x509.c
	${boringssl_source_path}/src/crypto/pem/pem_xaux.c
	${boringssl_source_path}/src/crypto/pkcs7/pkcs7.c
	${boringssl_source_path}/src/crypto/pkcs7/pkcs7_x509.c
	${boringssl_source_path}/src/crypto/pkcs8/p5_pbev2.c
	${boringssl_source_path}/src/crypto/pkcs8/pkcs8.c
	${boringssl_source_path}/src/crypto/pkcs8/pkcs8_x509.c
	${boringssl_source_path}/src/crypto/poly1305/poly1305.c
	${boringssl_source_path}/src/crypto/poly1305/poly1305_arm.c
	${boringssl_source_path}/src/crypto/poly1305/poly1305_vec.c
	${boringssl_source_path}/src/crypto/pool/pool.c
	${boringssl_source_path}/src/crypto/rand_extra/deterministic.c
	${boringssl_source_path}/src/crypto/rand_extra/forkunsafe.c
	${boringssl_source_path}/src/crypto/rand_extra/fuchsia.c
	${boringssl_source_path}/src/crypto/rand_extra/rand_extra.c
	${boringssl_source_path}/src/crypto/rand_extra/windows.c
	${boringssl_source_path}/src/crypto/rc4/rc4.c
	${boringssl_source_path}/src/crypto/refcount_c11.c
	${boringssl_source_path}/src/crypto/refcount_lock.c
	${boringssl_source_path}/src/crypto/rsa_extra/rsa_asn1.c
	${boringssl_source_path}/src/crypto/stack/stack.c
	${boringssl_source_path}/src/crypto/thread.c
	${boringssl_source_path}/src/crypto/thread_none.c
	${boringssl_source_path}/src/crypto/thread_pthread.c
	${boringssl_source_path}/src/crypto/thread_win.c
	${boringssl_source_path}/src/crypto/x509/a_digest.c
	${boringssl_source_path}/src/crypto/x509/a_sign.c
	${boringssl_source_path}/src/crypto/x509/a_strex.c
	${boringssl_source_path}/src/crypto/x509/a_verify.c
	${boringssl_source_path}/src/crypto/x509/algorithm.c
	${boringssl_source_path}/src/crypto/x509/asn1_gen.c
	${boringssl_source_path}/src/crypto/x509/by_dir.c
	${boringssl_source_path}/src/crypto/x509/by_file.c
	${boringssl_source_path}/src/crypto/x509/i2d_pr.c
	${boringssl_source_path}/src/crypto/x509/rsa_pss.c
	${boringssl_source_path}/src/crypto/x509/t_crl.c
	${boringssl_source_path}/src/crypto/x509/t_req.c
	${boringssl_source_path}/src/crypto/x509/t_x509.c
	${boringssl_source_path}/src/crypto/x509/t_x509a.c
	${boringssl_source_path}/src/crypto/x509/x509.c
	${boringssl_source_path}/src/crypto/x509/x509_att.c
	${boringssl_source_path}/src/crypto/x509/x509_cmp.c
	${boringssl_source_path}/src/crypto/x509/x509_d2.c
	${boringssl_source_path}/src/crypto/x509/x509_def.c
	${boringssl_source_path}/src/crypto/x509/x509_ext.c
	${boringssl_source_path}/src/crypto/x509/x509_lu.c
	${boringssl_source_path}/src/crypto/x509/x509_obj.c
	${boringssl_source_path}/src/crypto/x509/x509_r2x.c
	${boringssl_source_path}/src/crypto/x509/x509_req.c
	${boringssl_source_path}/src/crypto/x509/x509_set.c
	${boringssl_source_path}/src/crypto/x509/x509_trs.c
	${boringssl_source_path}/src/crypto/x509/x509_txt.c
	${boringssl_source_path}/src/crypto/x509/x509_v3.c
	${boringssl_source_path}/src/crypto/x509/x509_vfy.c
	${boringssl_source_path}/src/crypto/x509/x509_vpm.c
	${boringssl_source_path}/src/crypto/x509/x509cset.c
	${boringssl_source_path}/src/crypto/x509/x509name.c
	${boringssl_source_path}/src/crypto/x509/x509rset.c
	${boringssl_source_path}/src/crypto/x509/x509spki.c
	${boringssl_source_path}/src/crypto/x509/x_algor.c
	${boringssl_source_path}/src/crypto/x509/x_all.c
	${boringssl_source_path}/src/crypto/x509/x_attrib.c
	${boringssl_source_path}/src/crypto/x509/x_crl.c
	${boringssl_source_path}/src/crypto/x509/x_exten.c
	${boringssl_source_path}/src/crypto/x509/x_info.c
	${boringssl_source_path}/src/crypto/x509/x_name.c
	${boringssl_source_path}/src/crypto/x509/x_pkey.c
	${boringssl_source_path}/src/crypto/x509/x_pubkey.c
	${boringssl_source_path}/src/crypto/x509/x_req.c
	${boringssl_source_path}/src/crypto/x509/x_sig.c
	${boringssl_source_path}/src/crypto/x509/x_spki.c
	${boringssl_source_path}/src/crypto/x509/x_val.c
	${boringssl_source_path}/src/crypto/x509/x_x509.c
	${boringssl_source_path}/src/crypto/x509/x_x509a.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_cache.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_data.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_lib.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_map.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_node.c
	${boringssl_source_path}/src/crypto/x509v3/pcy_tree.c
	${boringssl_source_path}/src/crypto/x509v3/v3_akey.c
	${boringssl_source_path}/src/crypto/x509v3/v3_akeya.c
	${boringssl_source_path}/src/crypto/x509v3/v3_alt.c
	${boringssl_source_path}/src/crypto/x509v3/v3_bcons.c
	${boringssl_source_path}/src/crypto/x509v3/v3_bitst.c
	${boringssl_source_path}/src/crypto/x509v3/v3_conf.c
	${boringssl_source_path}/src/crypto/x509v3/v3_cpols.c
	${boringssl_source_path}/src/crypto/x509v3/v3_crld.c
	${boringssl_source_path}/src/crypto/x509v3/v3_enum.c
	${boringssl_source_path}/src/crypto/x509v3/v3_extku.c
	${boringssl_source_path}/src/crypto/x509v3/v3_genn.c
	${boringssl_source_path}/src/crypto/x509v3/v3_ia5.c
	${boringssl_source_path}/src/crypto/x509v3/v3_info.c
	${boringssl_source_path}/src/crypto/x509v3/v3_int.c
	${boringssl_source_path}/src/crypto/x509v3/v3_lib.c
	${boringssl_source_path}/src/crypto/x509v3/v3_ncons.c
	${boringssl_source_path}/src/crypto/x509v3/v3_ocsp.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pci.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pcia.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pcons.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pku.c
	${boringssl_source_path}/src/crypto/x509v3/v3_pmaps.c
	${boringssl_source_path}/src/crypto/x509v3/v3_prn.c
	${boringssl_source_path}/src/crypto/x509v3/v3_purp.c
	${boringssl_source_path}/src/crypto/x509v3/v3_skey.c
	${boringssl_source_path}/src/crypto/x509v3/v3_sxnet.c
	${boringssl_source_path}/src/crypto/x509v3/v3_utl.c
	${boringssl_source_path}/src/ssl/bio_ssl.cc
	${boringssl_source_path}/src/ssl/d1_both.cc
	${boringssl_source_path}/src/ssl/d1_lib.cc
	${boringssl_source_path}/src/ssl/d1_pkt.cc
	${boringssl_source_path}/src/ssl/d1_srtp.cc
	${boringssl_source_path}/src/ssl/dtls_method.cc
	${boringssl_source_path}/src/ssl/dtls_record.cc
	${boringssl_source_path}/src/ssl/handshake.cc
	${boringssl_source_path}/src/ssl/handshake_client.cc
	${boringssl_source_path}/src/ssl/handshake_server.cc
	${boringssl_source_path}/src/ssl/s3_both.cc
	${boringssl_source_path}/src/ssl/s3_lib.cc
	${boringssl_source_path}/src/ssl/s3_pkt.cc
	${boringssl_source_path}/src/ssl/ssl_aead_ctx.cc
	${boringssl_source_path}/src/ssl/ssl_asn1.cc
	${boringssl_source_path}/src/ssl/ssl_buffer.cc
	${boringssl_source_path}/src/ssl/ssl_cert.cc
	${boringssl_source_path}/src/ssl/ssl_cipher.cc
	${boringssl_source_path}/src/ssl/ssl_file.cc
	${boringssl_source_path}/src/ssl/ssl_key_share.cc
	${boringssl_source_path}/src/ssl/ssl_lib.cc
	${boringssl_source_path}/src/ssl/ssl_privkey.cc
	${boringssl_source_path}/src/ssl/ssl_session.cc
	${boringssl_source_path}/src/ssl/ssl_stat.cc
	${boringssl_source_path}/src/ssl/ssl_transcript.cc
	${boringssl_source_path}/src/ssl/ssl_versions.cc
	${boringssl_source_path}/src/ssl/ssl_x509.cc
	${boringssl_source_path}/src/ssl/t1_enc.cc
	${boringssl_source_path}/src/ssl/t1_lib.cc
	${boringssl_source_path}/src/ssl/tls13_both.cc
	${boringssl_source_path}/src/ssl/tls13_client.cc
	${boringssl_source_path}/src/ssl/tls13_enc.cc
	${boringssl_source_path}/src/ssl/tls13_server.cc
	${boringssl_source_path}/src/ssl/tls_method.cc
	${boringssl_source_path}/src/ssl/tls_record.cc
	${boringssl_source_path}/src/third_party/fiat/curve25519.c
	${jsoncpp_source_path}/src/lib_json/json_reader.cpp
	${jsoncpp_source_path}/src/lib_json/json_value.cpp
	${jsoncpp_source_path}/src/lib_json/json_writer.cpp
	${libyuv_source_path}/source/compare.cc
	${libyuv_source_path}/source/compare_common.cc
	${libyuv_source_path}/source/compare_gcc.cc
	${libyuv_source_path}/source/convert.cc
	${libyuv_source_path}/source/convert_argb.cc
	${libyuv_source_path}/source/convert_from.cc
	${libyuv_source_path}/source/convert_from_argb.cc
	${libyuv_source_path}/source/convert_jpeg.cc
	${libyuv_source_path}/source/convert_to_argb.cc
	${libyuv_source_path}/source/convert_to_i420.cc
	${libyuv_source_path}/source/cpu_id.cc
	${libyuv_source_path}/source/mjpeg_decoder.cc
	${libyuv_source_path}/source/mjpeg_validate.cc
	${libyuv_source_path}/source/planar_functions.cc
	${libyuv_source_path}/source/compare_neon.cc
	${libyuv_source_path}/source/compare_neon64.cc
	${libyuv_source_path}/source/rotate.cc
	${libyuv_source_path}/source/rotate_any.cc
	${libyuv_source_path}/source/rotate_argb.cc
	${libyuv_source_path}/source/rotate_common.cc
	${libyuv_source_path}/source/rotate_gcc.cc
	${libyuv_source_path}/source/rotate_neon.cc
	${libyuv_source_path}/source/rotate_neon64.cc
	${libyuv_source_path}/source/row_any.cc
	${libyuv_source_path}/source/row_common.cc
	${libyuv_source_path}/source/row_gcc.cc
	${libyuv_source_path}/source/row_neon.cc
	${libyuv_source_path}/source/row_neon64.cc
	${libyuv_source_path}/source/scale.cc
	${libyuv_source_path}/source/scale_any.cc
	${libyuv_source_path}/source/scale_argb.cc
	${libyuv_source_path}/source/scale_common.cc
	${libyuv_source_path}/source/scale_gcc.cc
	${libyuv_source_path}/source/scale_neon.cc
	${libyuv_source_path}/source/scale_neon64.cc
	${libyuv_source_path}/source/video_common.cc
	${CMAKE_CURRENT_SOURCE_DIR}/third_party/pffft/src/pffft.c
	${rnnoise_source_path}/rnn_vad_weights.cc
	${WEBRTC_LOCAL_SOURCES}
	$<TARGET_OBJECTS:libsrtp>
)

if (WTF_CPU_X86_64 OR WTF_CPU_X86)
	list(APPEND webrtc_SOURCES
		${webrtc_source_path}/common_audio/fir_filter_sse.cc
		${webrtc_source_path}/common_audio/resampler/sinc_resampler_sse.cc
		${webrtc_source_path}/modules/audio_processing/utility/ooura_fft_sse2.cc
		${webrtc_source_path}/modules/video_processing/util/denoiser_filter_sse2.cc
	)
endif()

add_library(webrtc STATIC ${webrtc_SOURCES})

target_compile_options(webrtc PRIVATE
	"$<$<COMPILE_LANGUAGE:CXX>:-std=gnu++11>"
	"-DWEBRTC_WEBKIT_BUILD=1"
	"-w"
)

target_compile_definitions(webrtc PRIVATE
	OPENSSL_NO_ASM
	DISABLE_H265
	DYNAMIC_ANNOTATIONS_ENABLED=1
	EXPAT_RELATIVE_PATH
	HAVE_LRINT
	HAVE_LRINTF
	HAVE_NETINET_IN_H
	HAVE_SCTP
	HAVE_WEBRTC_VIDEO
	HAVE_WEBRTC_VOICE
	JSON_USE_EXCEPTION=0
	NON_WINDOWS_DEFINE
	OPUS_BUILD
	OPUS_EXPORT=
	SCTP_SIMPLE_ALLOCATOR
	SCTP_USE_OPENSSL_SHA1
	VAR_ARRAYS
	WEBRTC_APM_DEBUG_DUMP=0
	WEBRTC_CODEC_G711
	WEBRTC_CODEC_G722
	WEBRTC_CODEC_ILBC
	WEBRTC_CODEC_ISAC
	WEBRTC_CODEC_OPUS
	WEBRTC_CODEC_RED
	WEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE
	WEBRTC_INTELLIGIBILITY_ENHANCER=0
	WEBRTC_POSIX
	WEBRTC_MAC
	WEBRTC_NS_FLOAT
	WEBRTC_OPUS_SUPPORT_120MS_PTIME=0
	WEBRTC_OPUS_VARIABLE_COMPLEXITY=0
	WEBRTC_USE_BUILTIN_OPUS=1
	WEBRTC_USE_BUILTIN_ISAC_FIX=1
	WEBRTC_USE_BUILTIN_ISAC_FLOAT=0
	WTF_USE_DYNAMIC_ANNOTATIONS=1
	RTC_DISABLE_VP9
	_GNU_SOURCE
	__Userspace__
	__Userspace_os_${CMAKE_HOST_SYSTEM_NAME}
)

if (WTF_CPU_ARM)
	target_compile_definitions(webrtc PRIVATE
		WEBRTC_ARCH_ARM=1
	)
elseif (WTF_CPU_ARM64)
	target_compile_definitions(webrtc PRIVATE
		WEBRTC_ARCH_ARM64=1
	)
endif()

target_include_directories(webrtc PRIVATE
	${CMAKE_CURRENT_SOURCE_DIR}/workaround
	${abseil_source_path}
	${boringssl_source_path}/src/include
	${jsoncpp_source_path}/include
	${jsoncpp_source_path}/src/lib_json
	${libsrtp_source_path}/config
	${libsrtp_source_path}/crypto/include
	${libsrtp_source_path}/include
	${libyuv_source_path}/include
	${rnnoise_source_path}
	${usrsctp_source_path}
	${usrsctp_source_path}/usrsctplib
	${usrsctp_source_path}/usrsctplib
	${usrsctp_source_path}/usrsctplib/netinet
	${webrtc_source_path}
	${webrtc_source_path}/common_audio/resampler/include
	${webrtc_source_path}/common_audio/signal_processing/include
	${webrtc_source_path}/common_audio/vad/include
	${webrtc_source_path}/modules/audio_coding/codecs/isac/main/include

	${CMAKE_CURRENT_SOURCE_DIR}
	${CMAKE_CURRENT_SOURCE_DIR}/third_party
	${CMAKE_CURRENT_SOURCE_DIR}/third_party/libsrtp/config
)

target_link_libraries(webrtc
	usrsctp
	opus
	jsoncpp_lib
)
